name: Upload Python Package

on:
    release:
        types:
            - published

permissions:
    contents: read

jobs:
    pypi-publish:
        name: upload release to PyPI
        runs-on: ubuntu-latest
        environment: release
        permissions:
            # IMPORTANT: this permission is mandatory for trusted publishing
            id-token: write
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
      
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: yarn
                cache-dependency-path: "nodejs/frontend/yarn.lock"

            - name: Generate artifacts
              run: |
                python3 -m pip install build packaging tqdm
                python3 -m script.shc_from_manifests
                python3 -m script.gen_requirements_all

            - name: Install dependencies
              run: nodejs/frontend/script/bootstrap

            - name: Build frontend
              run: nodejs/frontend/script/build_frontend

            - name: Build and release package
              # remove source package (about 670MB),
              # which can not be uploaded to PyPI (100MB max)
              run: |
                python3 -m build

            - name: Publish package distribution to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
